[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[language-server.pyright]
command = "pyright-python-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.typescript-language-server.config]
disableAutomaticTypingAcquisition = true
plugins = [{ name = "@vue/typescript-plugin", location = "vue-language-server", languages = ["vue"] }]

# [language-server.typescript-language-server.config.vue.inlayHints]
# includeInlayEnumMemberValueHints = true
# includeInlayFunctionLikeReturnTypeHints = true
# includeInlayFunctionParameterTypeHints = true
# includeInlayParameterNameHints = "all"
# includeInlayParameterNameHintsWhenArgumentMatchesName = true
# includeInlayPropertyDeclarationTypeHints = true
# includeInlayVariableTypeHints = true

[language-server.vuels]
command = "vue-language-server"
args = ["--stdio"]

[[language]]
name = "vue"
auto-format = true
file-types = ["vue", { glob = "*.vue.md" } ]
language-servers = ["typescript-language-server", "vuels"]
formatter = { command = 'prettier', args = ["--parser", "vue"] }

